name: Zampto Renew

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '5 3 * * 3'  # 每周三
    - cron: '5 4 * * 6'  # 每周六

jobs:
  run-zampto:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 检查 Secrets 是否设置
        run: |
          if [ -z "${{ secrets.USERNAME }}" ] || [ -z "${{ secrets.PASSWORD }}" ]; then
            echo "❌ USERNAME 或 PASSWORD 未设置，终止执行。"
            exit 1
          fi
          echo "✅ 账号信息已设置"
          
      - name: 执行 Zampto Renew 容器
        run: |
          docker run -it \
            -e USERNAME=${{ secrets.USERNAME }} \
            -e PASSWORD=${{ secrets.PASSWORD }} \
            -e TG_TOKEN=${{ secrets.TG_TOKEN }} \
            -e TG_USERID=${{ secrets.TG_USERID }} \
            -v ${{ github.workspace }}/zampto_server.py:/app/zampto_server.py \
            -v ${{ github.workspace }}/requirements.txt:/app/requirements.txt \
            ghcr.io/liveqte/zampto_renew:latest
